# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/linear_model/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.linear_model._base import LinearRegression as LinearRegression
from sklearn.linear_model._bayes import ARDRegression as ARDRegression, BayesianRidge as BayesianRidge
from sklearn.linear_model._coordinate_descent import (
    ElasticNet as ElasticNet,
    ElasticNetCV as ElasticNetCV,
    Lasso as Lasso,
    LassoCV as LassoCV,
    MultiTaskElasticNet as MultiTaskElasticNet,
    MultiTaskElasticNetCV as MultiTaskElasticNetCV,
    MultiTaskLasso as MultiTaskLasso,
    MultiTaskLassoCV as MultiTaskLassoCV,
    enet_path as enet_path,
    lasso_path as lasso_path,
)
from sklearn.linear_model._glm import GammaRegressor as GammaRegressor, PoissonRegressor as PoissonRegressor, TweedieRegressor as TweedieRegressor
from sklearn.linear_model._huber import HuberRegressor as HuberRegressor
from sklearn.linear_model._least_angle import (
    Lars as Lars,
    LarsCV as LarsCV,
    LassoLars as LassoLars,
    LassoLarsCV as LassoLarsCV,
    LassoLarsIC as LassoLarsIC,
    lars_path as lars_path,
    lars_path_gram as lars_path_gram,
)
from sklearn.linear_model._logistic import LogisticRegression as LogisticRegression, LogisticRegressionCV as LogisticRegressionCV
from sklearn.linear_model._omp import (
    OrthogonalMatchingPursuit as OrthogonalMatchingPursuit,
    OrthogonalMatchingPursuitCV as OrthogonalMatchingPursuitCV,
    orthogonal_mp as orthogonal_mp,
    orthogonal_mp_gram as orthogonal_mp_gram,
)
from sklearn.linear_model._passive_aggressive import (
    PassiveAggressiveClassifier as PassiveAggressiveClassifier,
    PassiveAggressiveRegressor as PassiveAggressiveRegressor,
)
from sklearn.linear_model._perceptron import Perceptron as Perceptron
from sklearn.linear_model._quantile import QuantileRegressor as QuantileRegressor
from sklearn.linear_model._ransac import RANSACRegressor as RANSACRegressor
from sklearn.linear_model._ridge import (
    Ridge as Ridge,
    RidgeClassifier as RidgeClassifier,
    RidgeClassifierCV as RidgeClassifierCV,
    RidgeCV as RidgeCV,
    ridge_regression as ridge_regression,
)
from sklearn.linear_model._sgd_fast import Hinge as Hinge, Huber as Huber, Log as Log, ModifiedHuber as ModifiedHuber, SquaredLoss as SquaredLoss
from sklearn.linear_model._stochastic_gradient import SGDClassifier as SGDClassifier, SGDOneClassSVM as SGDOneClassSVM, SGDRegressor as SGDRegressor
from sklearn.linear_model._theil_sen import TheilSenRegressor as TheilSenRegressor

__all__ = [
    "ARDRegression",
    "BayesianRidge",
    "ElasticNet",
    "ElasticNetCV",
    "Hinge",
    "Huber",
    "HuberRegressor",
    "Lars",
    "LarsCV",
    "Lasso",
    "LassoCV",
    "LassoLars",
    "LassoLarsCV",
    "LassoLarsIC",
    "LinearRegression",
    "Log",
    "LogisticRegression",
    "LogisticRegressionCV",
    "ModifiedHuber",
    "MultiTaskElasticNet",
    "MultiTaskElasticNetCV",
    "MultiTaskLasso",
    "MultiTaskLassoCV",
    "OrthogonalMatchingPursuit",
    "OrthogonalMatchingPursuitCV",
    "PassiveAggressiveClassifier",
    "PassiveAggressiveRegressor",
    "Perceptron",
    "QuantileRegressor",
    "Ridge",
    "RidgeCV",
    "RidgeClassifier",
    "RidgeClassifierCV",
    "SGDClassifier",
    "SGDRegressor",
    "SGDOneClassSVM",
    "SquaredLoss",
    "TheilSenRegressor",
    "enet_path",
    "lars_path",
    "lars_path_gram",
    "lasso_path",
    "orthogonal_mp",
    "orthogonal_mp_gram",
    "ridge_regression",
    "RANSACRegressor",
    "PoissonRegressor",
    "GammaRegressor",
    "TweedieRegressor",
]
