# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/experimental/enable_iterative_imputer.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn import impute as impute
from sklearn.impute._iterative import IterativeImputer as IterativeImputer
