# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/experimental/enable_halving_search_cv.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn import model_selection as model_selection
from sklearn.model_selection._search_successive_halving import (
    HalvingGridSearchCV as HalvingGridSearchCV,
    HalvingRandomSearchCV as HalvingRandomSearchCV,
)
