# Based on matplotlib 3.11.2, matplotlib/pyplot.py.
# Generated by typings/build_overlays.py; see typings/README.md.
"""
`matplotlib.pyplot` is a state-based interface to matplotlib. It provides
an implicit,  MATLAB-like, way of plotting.  It also opens figures on your
screen, and acts as the figure GUI manager.

pyplot is mainly intended for interactive plots and simple cases of
programmatic plot generation::

    import numpy as np
    import matplotlib.pyplot as plt

    x = np.arange(0, 5, 0.1)
    y = np.sin(x)
    plt.plot(x, y)
    plt.show()

The explicit object-oriented API is recommended for complex plots, though
pyplot is still usually used to create the figure and often the Axes in the
figure. See `.pyplot.figure`, `.pyplot.subplots`, and
`.pyplot.subplot_mosaic` to create figures, and
:doc:`Axes API </api/axes_api>` for the plotting methods on an Axes::

    import numpy as np
    import matplotlib.pyplot as plt

    x = np.arange(0, 5, 0.1)
    y = np.sin(x)
    fig, ax = plt.subplots()
    ax.plot(x, y)
    plt.show()


See :ref:`api_interfaces` for an explanation of the tradeoffs between the
implicit and explicit interfaces.
"""
from __future__ import annotations
from contextlib import AbstractContextManager, ExitStack
from enum import Enum
import functools
import importlib
import inspect
import logging
import sys
import threading
import time
from typing import IO, TYPE_CHECKING, cast, overload
from cycler import cycler
import matplotlib
import matplotlib.image
from matplotlib import _api
from matplotlib import get_backend as get_backend, rcParams as rcParams
from matplotlib import cm as cm
from matplotlib import style as style
from matplotlib import _pylab_helpers
from matplotlib import interactive
from matplotlib import cbook
from matplotlib import _docstring
from matplotlib.backend_bases import FigureCanvasBase, FigureManagerBase, MouseButton
from matplotlib.figure import Figure, FigureBase, figaspect
from matplotlib.gridspec import GridSpec, SubplotSpec
from matplotlib import rcsetup, rcParamsDefault, rcParamsOrig
from matplotlib.artist import Artist
from matplotlib.axes import Axes
from matplotlib.axes import Subplot
from matplotlib.backends import BackendFilter, backend_registry
from matplotlib.projections import PolarAxes
from matplotlib.colorizer import _ColorizerInterface, ColorizingArtist, Colorizer
from matplotlib import mlab
from matplotlib.scale import get_scale_names
from matplotlib.cm import _colormaps
from matplotlib.colors import _color_sequences, Colormap
import numpy as np
if TYPE_CHECKING:
    from collections.abc import Callable, Hashable, Iterable, Sequence
    import pathlib
    import os
    from typing import Any, BinaryIO, Literal, TypeVar
    from typing_extensions import ParamSpec
    import PIL.Image
    from numpy.typing import ArrayLike
    import pandas as pd
    import matplotlib.axes
    import matplotlib.artist
    import matplotlib.backend_bases
    from matplotlib.axis import Tick
    from matplotlib.axes._base import _AxesBase
    from matplotlib.backend_bases import CloseEvent, DrawEvent, KeyEvent, MouseEvent, PickEvent, ResizeEvent
    from matplotlib.cm import ScalarMappable
    from matplotlib.contour import ContourSet, QuadContourSet
    from matplotlib.collections import Collection, FillBetweenPolyCollection, LineCollection, PolyCollection, PathCollection, EventCollection, QuadMesh
    from matplotlib.colorbar import Colorbar
    from matplotlib.container import BarContainer, ErrorbarContainer, PieContainer, StemContainer
    from matplotlib.figure import SubFigure
    from matplotlib.legend import Legend
    from matplotlib.mlab import GaussianKDE
    from matplotlib.image import AxesImage, FigureImage
    from matplotlib.patches import FancyArrow, StepPatch
    from matplotlib.quiver import Barbs, Quiver, QuiverKey
    from matplotlib.scale import ScaleBase
    from matplotlib.typing import CloseEventType, ColorType, CoordsType, DataParamType, DrawEventType, HashableList, KeyEventType, LineStyleType, MarkerType, MouseEventType, PickEventType, RcGroupKeyType, RcKeyType, ResizeEventType, LogLevel
    from matplotlib.widgets import SubplotTool
    _P = ParamSpec('_P')
    _R = TypeVar('_R')
    _T = TypeVar('_T')
from matplotlib.colors import Normalize
from matplotlib.lines import Line2D, AxLine
from matplotlib.text import Text, Annotation
from matplotlib.patches import Arrow, Circle, Rectangle
from matplotlib.patches import Polygon
from matplotlib.widgets import Button, Slider, Widget
from matplotlib.ticker import TickHelper, Formatter, FixedFormatter, NullFormatter, FuncFormatter, FormatStrFormatter, ScalarFormatter, LogFormatter, LogFormatterExponent, LogFormatterMathtext, Locator, IndexLocator, FixedLocator, NullLocator, LinearLocator, LogLocator, AutoLocator, MultipleLocator, MaxNLocator
_log = logging.getLogger(__name__)
colormaps = _colormaps
color_sequences = _color_sequences

@overload
def _copy_docstring_and_deprecators(method: Any, func: Literal[None]=None) -> Callable[[Callable[_P, _R]], Callable[_P, _R]]:
    ...

@overload
def _copy_docstring_and_deprecators(method: Any, func: Callable[_P, _R]) -> Callable[_P, _R]:
    ...

def _copy_docstring_and_deprecators(method: Any, func: Callable[_P, _R] | None=None) -> Callable[[Callable[_P, _R]], Callable[_P, _R]] | Callable[_P, _R]:
    ...
_NO_PYPLOT_NOTE = ['FigureBase._gci', '_AxesBase._sci', 'Artist.findobj']

def _add_pyplot_note(func, wrapped_func):
    ...
_ReplDisplayHook = Enum('_ReplDisplayHook', ['NONE', 'PLAIN', 'IPYTHON'])
_REPL_DISPLAYHOOK = _ReplDisplayHook.NONE

def _draw_all_if_interactive() -> None:
    ...

def install_repl_displayhook() -> None:
    ...

def uninstall_repl_displayhook() -> None:
    ...
draw_all = _pylab_helpers.Gcf.draw_all

def set_loglevel(level: LogLevel) -> None:
    ...

def findobj(o: Artist | None=None, match: Callable[[Artist], bool] | type[Artist] | None=None, include_self: bool=True) -> list[Artist]:
    ...
_backend_mod: type[matplotlib.backend_bases._Backend] | None = None

def _get_backend_mod() -> type[matplotlib.backend_bases._Backend]:
    ...

def switch_backend(newbackend: str) -> None:
    ...

def _warn_if_gui_out_of_main_thread() -> None:
    ...

def new_figure_manager(*args, **kwargs):
    ...

def draw_if_interactive(*args, **kwargs):
    ...

@overload
def show(*, block: bool, **kwargs) -> None:
    ...

@overload
def show(*args: Any, **kwargs: Any) -> None:
    ...

def show(*args, **kwargs) -> None:
    ...

def isinteractive() -> bool:
    ...

def ioff() -> AbstractContextManager:
    ...

def ion() -> AbstractContextManager:
    ...

def pause(interval: float) -> None:
    ...

def rc(group: RcGroupKeyType, **kwargs) -> None:
    ...

def rc_context(rc: dict[RcKeyType, Any] | None=None, fname: str | pathlib.Path | os.PathLike[str] | None=None) -> AbstractContextManager[None]:
    ...

def rcdefaults() -> None:
    ...

def getp(obj, *args, **kwargs):
    ...

def get(obj, *args, **kwargs):
    ...

def setp(obj, *args, **kwargs):
    ...

def xkcd(scale: float=1, length: float=100, randomness: float=2) -> ExitStack:
    ...

def figure(num: int | str | Figure | SubFigure | None=None, figsize: ArrayLike | tuple[float, float, Literal['in', 'cm', 'px']] | None=None, dpi: float | None=None, *, facecolor: ColorType | None=None, edgecolor: ColorType | None=None, frameon: bool=True, FigureClass: type[Figure]=Figure, clear: bool=False, **kwargs) -> Figure:
    ...

def _auto_draw_if_interactive(fig, val):
    ...

def gcf() -> Figure:
    ...

def fignum_exists(num: int | str) -> bool:
    ...

def _raise_if_figure_exists(num, func_name, clear=False):
    ...

def get_fignums() -> list[int]:
    ...

def get_figlabels() -> list[Any]:
    ...

def get_current_fig_manager() -> FigureManagerBase | None:
    ...

@overload
def connect(s: MouseEventType, func: Callable[[MouseEvent], Any]) -> int:
    ...

@overload
def connect(s: KeyEventType, func: Callable[[KeyEvent], Any]) -> int:
    ...

@overload
def connect(s: PickEventType, func: Callable[[PickEvent], Any]) -> int:
    ...

@overload
def connect(s: ResizeEventType, func: Callable[[ResizeEvent], Any]) -> int:
    ...

@overload
def connect(s: CloseEventType, func: Callable[[CloseEvent], Any]) -> int:
    ...

@overload
def connect(s: DrawEventType, func: Callable[[DrawEvent], Any]) -> int:
    ...

def connect(s, func) -> int:
    ...

def disconnect(cid: int) -> None:
    ...

def close(fig: None | int | str | Figure | Literal['all']=None) -> None:
    ...

def clf() -> None:
    ...

def draw() -> None:
    ...

def savefig(fname: str | os.PathLike | IO, **kwargs) -> None:
    ...

def figlegend(*args, **kwargs) -> Legend:
    ...
if Figure.legend.__doc__:
    figlegend.__doc__ = Figure.legend.__doc__.replace(' legend(', ' figlegend(').replace('fig.legend(', 'plt.figlegend(').replace('ax.plot(', 'plt.plot(')

def axes(arg: None | tuple[float, float, float, float]=None, **kwargs) -> matplotlib.axes.Axes:
    ...

def delaxes(ax: matplotlib.axes.Axes | None=None) -> None:
    ...

def sca(ax: Axes) -> None:
    ...

def cla() -> None:
    ...

@overload
def subplot(nrows: int, ncols: int, index: int, /, **kwargs):
    ...

@overload
def subplot(pos: int | SubplotSpec, /, **kwargs):
    ...

@overload
def subplot(**kwargs):
    ...

def subplot(*args, **kwargs) -> Axes:
    ...

@overload
def subplots(nrows: Literal[1]=..., ncols: Literal[1]=..., *, sharex: bool | Literal['none', 'all', 'row', 'col']=..., sharey: bool | Literal['none', 'all', 'row', 'col']=..., squeeze: Literal[True]=..., width_ratios: Sequence[float] | None=..., height_ratios: Sequence[float] | None=..., subplot_kw: dict[str, Any] | None=..., gridspec_kw: dict[str, Any] | None=..., **fig_kw: Any) -> tuple[Figure, Axes]:
    ...

@overload
def subplots(nrows: int=..., ncols: int=..., *, sharex: bool | Literal['none', 'all', 'row', 'col']=..., sharey: bool | Literal['none', 'all', 'row', 'col']=..., squeeze: Literal[False], width_ratios: Sequence[float] | None=..., height_ratios: Sequence[float] | None=..., subplot_kw: dict[str, Any] | None=..., gridspec_kw: dict[str, Any] | None=..., **fig_kw: Any) -> tuple[Figure, np.ndarray]:
    ...

@overload
def subplots(nrows: int=..., ncols: int=..., *, sharex: bool | Literal['none', 'all', 'row', 'col']=..., sharey: bool | Literal['none', 'all', 'row', 'col']=..., squeeze: bool=..., width_ratios: Sequence[float] | None=..., height_ratios: Sequence[float] | None=..., subplot_kw: dict[str, Any] | None=..., gridspec_kw: dict[str, Any] | None=..., **fig_kw: Any) -> tuple[Figure, Any]:
    ...

def subplots(nrows: int=1, ncols: int=1, *, sharex: bool | Literal['none', 'all', 'row', 'col']=False, sharey: bool | Literal['none', 'all', 'row', 'col']=False, squeeze: bool=True, width_ratios: Sequence[float] | None=None, height_ratios: Sequence[float] | None=None, subplot_kw: dict[str, Any] | None=None, gridspec_kw: dict[str, Any] | None=None, **fig_kw: Any) -> tuple[Figure, Any]:
    ...

@overload
def subplot_mosaic(mosaic: str, *, sharex: bool=..., sharey: bool=..., width_ratios: ArrayLike | None=..., height_ratios: ArrayLike | None=..., empty_sentinel: str=..., subplot_kw: dict[str, Any] | None=..., gridspec_kw: dict[str, Any] | None=..., per_subplot_kw: dict[str | tuple[str, ...], dict[str, Any]] | None=..., **fig_kw: Any) -> tuple[Figure, dict[str, matplotlib.axes.Axes]]:
    ...

@overload
def subplot_mosaic(mosaic: list[HashableList[_T]], *, sharex: bool=..., sharey: bool=..., width_ratios: ArrayLike | None=..., height_ratios: ArrayLike | None=..., empty_sentinel: _T=..., subplot_kw: dict[str, Any] | None=..., gridspec_kw: dict[str, Any] | None=..., per_subplot_kw: dict[_T | tuple[_T, ...], dict[str, Any]] | None=..., **fig_kw: Any) -> tuple[Figure, dict[_T, matplotlib.axes.Axes]]:
    ...

@overload
def subplot_mosaic(mosaic: list[HashableList[Hashable]], *, sharex: bool=..., sharey: bool=..., width_ratios: ArrayLike | None=..., height_ratios: ArrayLike | None=..., empty_sentinel: Any=..., subplot_kw: dict[str, Any] | None=..., gridspec_kw: dict[str, Any] | None=..., per_subplot_kw: dict[Hashable | tuple[Hashable, ...], dict[str, Any]] | None=..., **fig_kw: Any) -> tuple[Figure, dict[Hashable, matplotlib.axes.Axes]]:
    ...

def subplot_mosaic(mosaic: str | list[HashableList[_T]] | list[HashableList[Hashable]], *, sharex: bool=False, sharey: bool=False, width_ratios: ArrayLike | None=None, height_ratios: ArrayLike | None=None, empty_sentinel: Any='.', subplot_kw: dict[str, Any] | None=None, gridspec_kw: dict[str, Any] | None=None, per_subplot_kw: dict[str | tuple[str, ...], dict[str, Any]] | dict[_T | tuple[_T, ...], dict[str, Any]] | dict[Hashable | tuple[Hashable, ...], dict[str, Any]] | None=None, **fig_kw: Any) -> tuple[Figure, dict[str, matplotlib.axes.Axes]] | tuple[Figure, dict[_T, matplotlib.axes.Axes]] | tuple[Figure, dict[Hashable, matplotlib.axes.Axes]]:
    ...

def subplot2grid(shape: tuple[int, int], loc: tuple[int, int], rowspan: int=1, colspan: int=1, fig: Figure | None=None, **kwargs) -> matplotlib.axes.Axes:
    ...

def twinx(ax: matplotlib.axes.Axes | None=None) -> _AxesBase:
    ...

def twiny(ax: matplotlib.axes.Axes | None=None) -> _AxesBase:
    ...

def subplot_tool(targetfig: Figure | None=None) -> SubplotTool | None:
    ...

def box(on: bool | None=None) -> None:
    ...

@overload
def xlim() -> tuple[float, float]:
    ...

@overload
def xlim(left: float | tuple[float, float] | None=None, right: float | None=None, *, emit: bool=True, auto: bool | None=False, xmin: float | None=None, xmax: float | None=None) -> tuple[float, float]:
    ...

def xlim(*args, **kwargs) -> tuple[float, float]:
    ...

@overload
def ylim() -> tuple[float, float]:
    ...

@overload
def ylim(bottom: float | tuple[float, float] | None=None, top: float | None=None, *, emit: bool=True, auto: bool | None=False, ymin: float | None=None, ymax: float | None=None) -> tuple[float, float]:
    ...

def ylim(*args, **kwargs) -> tuple[float, float]:
    ...

def xticks(ticks: ArrayLike | None=None, labels: Sequence[str] | None=None, *, minor: bool=False, **kwargs) -> tuple[list[Tick] | np.ndarray, list[Text]]:
    ...

def yticks(ticks: ArrayLike | None=None, labels: Sequence[str] | None=None, *, minor: bool=False, **kwargs) -> tuple[list[Tick] | np.ndarray, list[Text]]:
    ...

def rgrids(radii: ArrayLike | None=None, labels: Sequence[str | Text] | None=None, angle: float | None=None, fmt: str | None=None, **kwargs) -> tuple[list[Line2D], list[Text]]:
    ...

def thetagrids(angles: ArrayLike | None=None, labels: Sequence[str | Text] | None=None, fmt: str | None=None, **kwargs) -> tuple[list[Line2D], list[Text]]:
    ...

def get_plot_commands() -> list[str]:
    ...

def _get_pyplot_commands() -> list[str]:
    ...

def colorbar(mappable: ScalarMappable | ColorizingArtist | None=None, cax: matplotlib.axes.Axes | None=None, ax: matplotlib.axes.Axes | Iterable[matplotlib.axes.Axes] | None=None, **kwargs) -> Colorbar:
    ...

def clim(vmin: float | None=None, vmax: float | None=None) -> None:
    ...

def get_cmap(name: Colormap | str | None=None, lut: int | None=None) -> Colormap:
    ...

def set_cmap(cmap: Colormap | str) -> None:
    ...

def imread(fname: str | pathlib.Path | BinaryIO, format: str | None=None) -> np.ndarray:
    ...

def imsave(fname: str | os.PathLike | BinaryIO, arr: ArrayLike, **kwargs) -> None:
    ...

def matshow(A: ArrayLike, fignum: None | int=None, **kwargs) -> AxesImage:
    ...

def polar(*args, **kwargs) -> list[Line2D]:
    ...
if rcParams['backend_fallback']:
    requested_backend = rcParams._get_backend_or_none()
    requested_backend = None if requested_backend is None else requested_backend.lower()
    available_backends = backend_registry.list_builtin(BackendFilter.INTERACTIVE)
    if requested_backend in set(available_backends) - {'webagg', 'nbagg'} and cbook._get_running_interactive_framework():
        rcParams._set('backend', rcsetup._auto_backend_sentinel)

def figimage(X: ArrayLike, xo: int=0, yo: int=0, alpha: float | None=None, norm: str | Normalize | None=None, cmap: str | Colormap | None=None, vmin: float | None=None, vmax: float | None=None, origin: Literal['upper', 'lower'] | None=None, resize: bool=False, *, colorizer: Colorizer | None=None, **kwargs) -> FigureImage:
    ...

def figtext(x: float, y: float, s: str, fontdict: dict[str, Any] | None=None, **kwargs) -> Text:
    ...

def gca() -> Axes:
    ...

def gci() -> ColorizingArtist | None:
    ...

def ginput(n: int=1, timeout: float=30, show_clicks: bool=True, mouse_add: MouseButton=MouseButton.LEFT, mouse_pop: MouseButton=MouseButton.RIGHT, mouse_stop: MouseButton=MouseButton.MIDDLE) -> list[tuple[int, int]]:
    ...

def subplots_adjust(left: float | None=None, bottom: float | None=None, right: float | None=None, top: float | None=None, wspace: float | None=None, hspace: float | None=None) -> None:
    ...

def suptitle(t: str, **kwargs) -> Text:
    ...

def tight_layout(*, pad: float=1.08, h_pad: float | None=None, w_pad: float | None=None, rect: tuple[float, float, float, float] | None=None) -> None:
    ...

def waitforbuttonpress(timeout: float=-1) -> None | bool:
    ...

def acorr(x: ArrayLike, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray, LineCollection | Line2D, Line2D | None]:
    ...

def angle_spectrum(x: ArrayLike, Fs: float | None=None, Fc: int | None=None, window: Callable[[ArrayLike], ArrayLike] | ArrayLike | None=None, pad_to: int | None=None, sides: Literal['default', 'onesided', 'twosided'] | None=None, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray, Line2D]:
    ...

def annotate(text: str, xy: tuple[Any, Any], xytext: tuple[Any, Any] | None=None, xycoords: CoordsType='data', textcoords: CoordsType | None=None, arrowprops: dict[str, Any] | None=None, annotation_clip: bool | None=None, **kwargs) -> Annotation:
    ...

def arrow(x: float, y: float, dx: float, dy: float, **kwargs) -> FancyArrow:
    ...

def autoscale(enable: bool=True, axis: Literal['both', 'x', 'y']='both', tight: bool | None=None) -> None:
    ...

def axhline(y: float=0, xmin: float=0, xmax: float=1, **kwargs) -> Line2D:
    ...

def axhspan(ymin: float, ymax: float, xmin: float=0, xmax: float=1, **kwargs) -> Rectangle:
    ...

def axis(arg: tuple[float, float, float, float] | bool | str | None=None, /, *, emit: bool=True, **kwargs) -> tuple[float, float, float, float]:
    ...

def axline(xy1: tuple[float, float], xy2: tuple[float, float] | None=None, *, slope: float | None=None, **kwargs) -> AxLine:
    ...

def axvline(x: float=0, ymin: float=0, ymax: float=1, **kwargs) -> Line2D:
    ...

def axvspan(xmin: float, xmax: float, ymin: float=0, ymax: float=1, **kwargs) -> Rectangle:
    ...

def bar(x: float | ArrayLike, height: float | ArrayLike, width: float | ArrayLike=0.8, bottom: float | ArrayLike | None=None, *, align: Literal['center', 'edge']='center', data: DataParamType=None, **kwargs) -> BarContainer:
    ...

def barbs(*args, data: DataParamType=None, **kwargs) -> Barbs:
    ...

def barh(y: float | ArrayLike, width: float | ArrayLike, height: float | ArrayLike=0.8, left: float | ArrayLike | None=None, *, align: Literal['center', 'edge']='center', data: DataParamType=None, **kwargs) -> BarContainer:
    ...

def bar_label(container: BarContainer, labels: ArrayLike | None=None, *, fmt: str | Callable[[float], str]='%g', label_type: Literal['center', 'edge']='edge', padding: float | ArrayLike=0, **kwargs) -> list[Annotation]:
    ...

def boxplot(x: ArrayLike | Sequence[ArrayLike], notch: bool | None=None, sym: str | None=None, vert: bool | None=None, orientation: Literal['vertical', 'horizontal']='vertical', whis: float | tuple[float, float] | None=None, positions: ArrayLike | None=None, widths: float | ArrayLike | None=None, patch_artist: bool | None=None, bootstrap: int | None=None, usermedians: ArrayLike | None=None, conf_intervals: ArrayLike | None=None, meanline: bool | None=None, showmeans: bool | None=None, showcaps: bool | None=None, showbox: bool | None=None, showfliers: bool | None=None, boxprops: dict[str, Any] | None=None, tick_labels: Sequence[str] | None=None, flierprops: dict[str, Any] | None=None, medianprops: dict[str, Any] | None=None, meanprops: dict[str, Any] | None=None, capprops: dict[str, Any] | None=None, whiskerprops: dict[str, Any] | None=None, manage_ticks: bool=True, autorange: bool=False, zorder: float | None=None, capwidths: float | ArrayLike | None=None, label: Sequence[str] | None=None, *, data: DataParamType=None) -> dict[str, Any]:
    ...

def broken_barh(xranges: Sequence[tuple[float, float]], yrange: tuple[float, float], align: Literal['bottom', 'center', 'top']='bottom', *, data: DataParamType=None, **kwargs) -> PolyCollection:
    ...

def clabel(CS: ContourSet, levels: ArrayLike | None=None, **kwargs) -> list[Text]:
    ...

def cohere(x: ArrayLike, y: ArrayLike, NFFT: int=256, Fs: float=2, Fc: int=0, detrend: Literal['none', 'mean', 'linear'] | Callable[[ArrayLike], ArrayLike]=mlab.detrend_none, window: Callable[[ArrayLike], ArrayLike] | ArrayLike=mlab.window_hanning, noverlap: int=0, pad_to: int | None=None, sides: Literal['default', 'onesided', 'twosided']='default', scale_by_freq: bool | None=None, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray]:
    ...

def contour(*args, data: DataParamType=None, **kwargs) -> QuadContourSet:
    ...

def contourf(*args, data: DataParamType=None, **kwargs) -> QuadContourSet:
    ...

def csd(x: ArrayLike, y: ArrayLike, NFFT: int | None=None, Fs: float | None=None, Fc: int | None=None, detrend: Literal['none', 'mean', 'linear'] | Callable[[ArrayLike], ArrayLike] | None=None, window: Callable[[ArrayLike], ArrayLike] | ArrayLike | None=None, noverlap: int | None=None, pad_to: int | None=None, sides: Literal['default', 'onesided', 'twosided'] | None=None, scale_by_freq: bool | None=None, return_line: bool | None=None, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray] | tuple[np.ndarray, np.ndarray, Line2D]:
    ...

def ecdf(x: ArrayLike, weights: ArrayLike | None=None, *, complementary: bool=False, orientation: Literal['vertical', 'horizontal']='vertical', compress: bool=False, data: DataParamType=None, **kwargs) -> Line2D:
    ...

def errorbar(x: float | ArrayLike, y: float | ArrayLike, yerr: float | ArrayLike | None=None, xerr: float | ArrayLike | None=None, fmt: str='', ecolor: ColorType | None=None, elinewidth: float | None=None, capsize: float | None=None, barsabove: bool=False, lolims: bool | ArrayLike=False, uplims: bool | ArrayLike=False, xlolims: bool | ArrayLike=False, xuplims: bool | ArrayLike=False, errorevery: int | tuple[int, int]=1, capthick: float | None=None, elinestyle: LineStyleType | None=None, *, data: DataParamType=None, **kwargs) -> ErrorbarContainer:
    ...

def eventplot(positions: ArrayLike | Sequence[ArrayLike], orientation: Literal['horizontal', 'vertical']='horizontal', lineoffsets: float | Sequence[float]=1, linelengths: float | Sequence[float]=1, linewidths: float | Sequence[float] | None=None, colors: ColorType | Sequence[ColorType] | None=None, alpha: float | Sequence[float] | None=None, linestyles: LineStyleType | Sequence[LineStyleType]='solid', *, data: DataParamType=None, **kwargs) -> EventCollection:
    ...

def fill(*args, data: DataParamType=None, **kwargs) -> list[Polygon]:
    ...

def fill_between(x: ArrayLike, y1: ArrayLike | float, y2: ArrayLike | float=0, where: ArrayLike | None=None, interpolate: bool=False, step: Literal['pre', 'post', 'mid'] | None=None, *, data: DataParamType=None, **kwargs) -> FillBetweenPolyCollection:
    ...

def fill_betweenx(y: ArrayLike, x1: ArrayLike | float, x2: ArrayLike | float=0, where: ArrayLike | None=None, step: Literal['pre', 'post', 'mid'] | None=None, interpolate: bool=False, *, data: DataParamType=None, **kwargs) -> FillBetweenPolyCollection:
    ...

def grid(visible: bool | None=None, which: Literal['major', 'minor', 'both']='major', axis: Literal['both', 'x', 'y']='both', **kwargs) -> None:
    ...

def grouped_bar(heights: Sequence[ArrayLike] | dict[str, ArrayLike] | np.ndarray | pd.DataFrame, *, positions: ArrayLike | None=None, group_spacing: float | None=1.5, bar_spacing: float | None=0, tick_labels: Sequence[str] | None=None, labels: Sequence[str] | None=None, orientation: Literal['vertical', 'horizontal']='vertical', colors: Iterable[ColorType] | None=None, **kwargs) -> list[BarContainer]:
    ...

def hexbin(x: ArrayLike, y: ArrayLike, C: ArrayLike | None=None, gridsize: int | tuple[int, int]=100, bins: Literal['log'] | int | Sequence[float] | None=None, xscale: Literal['linear', 'log']='linear', yscale: Literal['linear', 'log']='linear', extent: tuple[float, float, float, float] | None=None, cmap: str | Colormap | None=None, norm: str | Normalize | None=None, vmin: float | None=None, vmax: float | None=None, alpha: float | None=None, linewidths: float | None=None, edgecolors: Literal['face', 'none'] | ColorType='face', reduce_C_function: Callable[[np.ndarray | list[float]], float]=np.mean, mincnt: int | None=None, marginals: bool=False, colorizer: Colorizer | None=None, *, data: DataParamType=None, **kwargs) -> PolyCollection:
    ...

def hist(x: ArrayLike | Sequence[ArrayLike], bins: int | Sequence[float] | str | None=None, range: tuple[float, float] | None=None, density: bool=False, weights: ArrayLike | None=None, cumulative: bool | float=False, bottom: ArrayLike | float | None=None, histtype: Literal['bar', 'barstacked', 'step', 'stepfilled']='bar', align: Literal['left', 'mid', 'right']='mid', orientation: Literal['vertical', 'horizontal']='vertical', rwidth: float | None=None, log: bool=False, color: ColorType | Sequence[ColorType] | None=None, label: str | Sequence[str] | None=None, stacked: bool=False, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray | list[np.ndarray], np.ndarray, BarContainer | Polygon | list[BarContainer | Polygon]]:
    ...

def stairs(values: ArrayLike, edges: ArrayLike | None=None, *, orientation: Literal['vertical', 'horizontal']='vertical', baseline: float | ArrayLike | None=0, fill: bool=False, data: DataParamType=None, **kwargs) -> StepPatch:
    ...

def hist2d(x: ArrayLike, y: ArrayLike, bins: None | int | tuple[int, int] | ArrayLike | tuple[ArrayLike, ArrayLike]=10, range: ArrayLike | None=None, density: bool=False, weights: ArrayLike | None=None, cmin: float | None=None, cmax: float | None=None, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray, np.ndarray, QuadMesh]:
    ...

def hlines(y: float | ArrayLike, xmin: float | ArrayLike, xmax: float | ArrayLike, colors: ColorType | Sequence[ColorType] | None=None, linestyles: LineStyleType='solid', label: str='', *, data: DataParamType=None, **kwargs) -> LineCollection:
    ...

def imshow(X: ArrayLike | PIL.Image.Image, cmap: str | Colormap | None=None, norm: str | Normalize | None=None, *, aspect: Literal['equal', 'auto'] | float | None=None, interpolation: str | None=None, alpha: float | ArrayLike | None=None, vmin: float | None=None, vmax: float | None=None, colorizer: Colorizer | None=None, origin: Literal['upper', 'lower'] | None=None, extent: tuple[float, float, float, float] | None=None, interpolation_stage: Literal['data', 'rgba', 'auto'] | None=None, filternorm: bool=True, filterrad: float=4.0, resample: bool | None=None, url: str | None=None, data: DataParamType=None, **kwargs) -> AxesImage:
    ...

def legend(*args, **kwargs) -> Legend:
    ...

def locator_params(axis: Literal['both', 'x', 'y']='both', tight: bool | None=None, **kwargs) -> None:
    ...

def loglog(*args, **kwargs) -> list[Line2D]:
    ...

def magnitude_spectrum(x: ArrayLike, Fs: float | None=None, Fc: int | None=None, window: Callable[[ArrayLike], ArrayLike] | ArrayLike | None=None, pad_to: int | None=None, sides: Literal['default', 'onesided', 'twosided'] | None=None, scale: Literal['default', 'linear', 'dB'] | None=None, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray, Line2D]:
    ...

def margins(*margins: float, x: float | None=None, y: float | None=None, tight: bool | None=True) -> tuple[float, float] | None:
    ...

def minorticks_off() -> None:
    ...

def minorticks_on() -> None:
    ...

def pcolor(*args: ArrayLike, shading: Literal['flat', 'nearest', 'auto'] | None=None, alpha: float | None=None, norm: str | Normalize | None=None, cmap: str | Colormap | None=None, vmin: float | None=None, vmax: float | None=None, colorizer: Colorizer | None=None, data: DataParamType=None, **kwargs) -> Collection:
    ...

def pcolormesh(*args: ArrayLike, alpha: float | None=None, norm: str | Normalize | None=None, cmap: str | Colormap | None=None, vmin: float | None=None, vmax: float | None=None, colorizer: Colorizer | None=None, shading: Literal['flat', 'nearest', 'gouraud', 'auto'] | None=None, antialiased: bool=False, data: DataParamType=None, **kwargs) -> QuadMesh:
    ...

def phase_spectrum(x: ArrayLike, Fs: float | None=None, Fc: int | None=None, window: Callable[[ArrayLike], ArrayLike] | ArrayLike | None=None, pad_to: int | None=None, sides: Literal['default', 'onesided', 'twosided'] | None=None, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray, Line2D]:
    ...

def pie(x: ArrayLike, explode: ArrayLike | None=None, labels: Sequence[str] | None=None, colors: ColorType | Sequence[ColorType] | None=None, autopct: str | Callable[[float], str] | None=None, pctdistance: float=0.6, shadow: bool=False, labeldistance: float | None=1.1, startangle: float=0, radius: float=1, counterclock: bool=True, wedgeprops: dict[str, Any] | None=None, textprops: dict[str, Any] | None=None, center: tuple[float, float]=(0, 0), frame: bool=False, rotatelabels: bool=False, *, normalize: bool=True, hatch: str | Sequence[str] | None=None, data: DataParamType=None) -> PieContainer:
    ...

def pie_label(container: PieContainer, /, labels: str | Sequence[str], *, distance: float=0.6, textprops: dict | None=None, rotate: bool=False, alignment: str='auto') -> list[Text]:
    ...

def plot(*args: float | ArrayLike | str, scalex: bool=True, scaley: bool=True, data: DataParamType=None, **kwargs) -> list[Line2D]:
    ...

def psd(x: ArrayLike, NFFT: int | None=None, Fs: float | None=None, Fc: int | None=None, detrend: Literal['none', 'mean', 'linear'] | Callable[[ArrayLike], ArrayLike] | None=None, window: Callable[[ArrayLike], ArrayLike] | ArrayLike | None=None, noverlap: int | None=None, pad_to: int | None=None, sides: Literal['default', 'onesided', 'twosided'] | None=None, scale_by_freq: bool | None=None, return_line: bool | None=None, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray] | tuple[np.ndarray, np.ndarray, Line2D]:
    ...

def quiver(*args, data: DataParamType=None, **kwargs) -> Quiver:
    ...

def quiverkey(Q: Quiver, X: float, Y: float, U: float, label: str, **kwargs) -> QuiverKey:
    ...

def scatter(x: float | ArrayLike, y: float | ArrayLike, s: float | ArrayLike | None=None, c: ArrayLike | Sequence[ColorType] | ColorType | None=None, marker: MarkerType | None=None, cmap: str | Colormap | None=None, norm: str | Normalize | None=None, vmin: float | None=None, vmax: float | None=None, alpha: float | None=None, linewidths: float | Sequence[float] | None=None, *, edgecolors: Literal['face', 'none'] | ColorType | Sequence[ColorType] | None=None, colorizer: Colorizer | None=None, plotnonfinite: bool=False, data: DataParamType=None, **kwargs) -> PathCollection:
    ...

def semilogx(*args, **kwargs) -> list[Line2D]:
    ...

def semilogy(*args, **kwargs) -> list[Line2D]:
    ...

def specgram(x: ArrayLike, NFFT: int | None=None, Fs: float | None=None, Fc: int | None=None, detrend: Literal['none', 'mean', 'linear'] | Callable[[ArrayLike], ArrayLike] | None=None, window: Callable[[ArrayLike], ArrayLike] | ArrayLike | None=None, noverlap: int | None=None, cmap: str | Colormap | None=None, xextent: tuple[float, float] | None=None, pad_to: int | None=None, sides: Literal['default', 'onesided', 'twosided'] | None=None, scale_by_freq: bool | None=None, mode: Literal['default', 'psd', 'magnitude', 'angle', 'phase'] | None=None, scale: Literal['default', 'linear', 'dB'] | None=None, vmin: float | None=None, vmax: float | None=None, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray, np.ndarray, AxesImage]:
    ...

def spy(Z: ArrayLike, precision: float | Literal['present']=0, marker: str | None=None, markersize: float | None=None, aspect: Literal['equal', 'auto'] | float | None='equal', origin: Literal['upper', 'lower']='upper', **kwargs) -> AxesImage:
    ...

def stackplot(x, *args, labels=(), colors=None, baseline='zero', data=None, **kwargs):
    ...

def stem(*args: ArrayLike | str, linefmt: str | None=None, markerfmt: str | None=None, basefmt: str | None=None, bottom: float=0, label: str | None=None, orientation: Literal['vertical', 'horizontal']='vertical', data: DataParamType=None) -> StemContainer:
    ...

def step(x: ArrayLike, y: ArrayLike, *args, where: Literal['pre', 'post', 'mid']='pre', data: DataParamType=None, **kwargs) -> list[Line2D]:
    ...

def streamplot(x, y, u, v, density=1, linewidth=None, color=None, cmap=None, norm=None, arrowsize=1, arrowstyle='-|>', minlength=0.1, transform=None, zorder=None, start_points=None, maxlength=4.0, integration_direction='both', broken_streamlines=True, *, integration_max_step_scale=1.0, integration_max_error_scale=1.0, num_arrows=1, data=None):
    ...

def table(cellText=None, cellColours=None, cellLoc='right', colWidths=None, rowLabels=None, rowColours=None, rowLoc='left', colLabels=None, colColours=None, colLoc='center', loc='bottom', bbox=None, edges='closed', **kwargs):
    ...

def text(x: float, y: float, s: str, fontdict: dict[str, Any] | None=None, **kwargs) -> Text:
    ...

def tick_params(axis: Literal['both', 'x', 'y']='both', **kwargs) -> None:
    ...

def ticklabel_format(*, axis: Literal['both', 'x', 'y']='both', style: Literal['', 'sci', 'scientific', 'plain'] | None=None, scilimits: tuple[int, int] | None=None, useOffset: bool | float | None=None, useLocale: bool | None=None, useMathText: bool | None=None) -> None:
    ...

def tricontour(*args, **kwargs):
    ...

def tricontourf(*args, **kwargs):
    ...

def tripcolor(*args, alpha=1.0, norm=None, cmap=None, vmin=None, vmax=None, shading='flat', facecolors=None, **kwargs):
    ...

def triplot(*args, **kwargs):
    ...

def violinplot(dataset: ArrayLike | Sequence[ArrayLike], positions: ArrayLike | None=None, vert: bool | None=None, orientation: Literal['vertical', 'horizontal']='vertical', widths: float | ArrayLike=0.5, showmeans: bool=False, showextrema: bool=True, showmedians: bool=False, quantiles: Sequence[float | Sequence[float]] | None=None, points: int=100, bw_method: Literal['scott', 'silverman'] | float | Callable[[GaussianKDE], float] | None=None, side: Literal['both', 'low', 'high']='both', facecolor: Sequence[ColorType] | ColorType | None=None, linecolor: Sequence[ColorType] | ColorType | None=None, *, data: DataParamType=None) -> dict[str, Collection]:
    ...

def vlines(x: float | ArrayLike, ymin: float | ArrayLike, ymax: float | ArrayLike, colors: ColorType | Sequence[ColorType] | None=None, linestyles: LineStyleType='solid', label: str='', *, data: DataParamType=None, **kwargs) -> LineCollection:
    ...

def xcorr(x: ArrayLike, y: ArrayLike, normed: bool=True, detrend: Callable[[ArrayLike], ArrayLike]=mlab.detrend_none, usevlines: bool=True, maxlags: int=10, *, data: DataParamType=None, **kwargs) -> tuple[np.ndarray, np.ndarray, LineCollection | Line2D, Line2D | None]:
    ...

def sci(im: ColorizingArtist) -> None:
    ...

def title(label: str, fontdict: dict[str, Any] | None=None, loc: Literal['left', 'center', 'right'] | None=None, pad: float | None=None, *, y: float | None=None, **kwargs) -> Text:
    ...

def xlabel(xlabel: str, fontdict: dict[str, Any] | None=None, labelpad: float | None=None, *, loc: Literal['left', 'center', 'right'] | None=None, **kwargs) -> Text:
    ...

def ylabel(ylabel: str, fontdict: dict[str, Any] | None=None, labelpad: float | None=None, *, loc: Literal['bottom', 'center', 'top'] | None=None, **kwargs) -> Text:
    ...

def xscale(value: str | ScaleBase, **kwargs) -> None:
    ...

def yscale(value: str | ScaleBase, **kwargs) -> None:
    ...

def autumn() -> None:
    ...

def bone() -> None:
    ...

def cool() -> None:
    ...

def copper() -> None:
    ...

def flag() -> None:
    ...

def gray() -> None:
    ...

def hot() -> None:
    ...

def hsv() -> None:
    ...

def jet() -> None:
    ...

def pink() -> None:
    ...

def prism() -> None:
    ...

def spring() -> None:
    ...

def summer() -> None:
    ...

def winter() -> None:
    ...

def magma() -> None:
    ...

def inferno() -> None:
    ...

def plasma() -> None:
    ...

def viridis() -> None:
    ...

def nipy_spectral() -> None:
    ...
