# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/metrics/cluster/_bicluster.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from typing import Callable, Literal

from numpy import ndarray

from sklearn._typing import Float

__all__ = ["consensus_score"]

def consensus_score(
    a: tuple[ndarray, ndarray] | tuple[int, int],
    b: tuple[ndarray, ndarray] | tuple[int, int],
    *,
    similarity: Literal["jaccard"] | Callable = "jaccard",
) -> Float: ...
