# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/ensemble/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.ensemble._bagging import BaggingClassifier as BaggingClassifier, BaggingRegressor as BaggingRegressor
from sklearn.ensemble._base import BaseEnsemble as BaseEnsemble
from sklearn.ensemble._forest import (
    ExtraTreesClassifier as ExtraTreesClassifier,
    ExtraTreesRegressor as ExtraTreesRegressor,
    RandomForestClassifier as RandomForestClassifier,
    RandomForestRegressor as RandomForestRegressor,
    RandomTreesEmbedding as RandomTreesEmbedding,
)
from sklearn.ensemble._gb import GradientBoostingClassifier as GradientBoostingClassifier, GradientBoostingRegressor as GradientBoostingRegressor
from sklearn.ensemble._hist_gradient_boosting.gradient_boosting import (
    HistGradientBoostingClassifier as HistGradientBoostingClassifier,
    HistGradientBoostingRegressor as HistGradientBoostingRegressor,
)
from sklearn.ensemble._iforest import IsolationForest as IsolationForest
from sklearn.ensemble._stacking import StackingClassifier as StackingClassifier, StackingRegressor as StackingRegressor
from sklearn.ensemble._voting import VotingClassifier as VotingClassifier, VotingRegressor as VotingRegressor
from sklearn.ensemble._weight_boosting import AdaBoostClassifier as AdaBoostClassifier, AdaBoostRegressor as AdaBoostRegressor

__all__ = [
    "BaseEnsemble",
    "RandomForestClassifier",
    "RandomForestRegressor",
    "RandomTreesEmbedding",
    "ExtraTreesClassifier",
    "ExtraTreesRegressor",
    "BaggingClassifier",
    "BaggingRegressor",
    "IsolationForest",
    "GradientBoostingClassifier",
    "GradientBoostingRegressor",
    "AdaBoostClassifier",
    "AdaBoostRegressor",
    "VotingClassifier",
    "VotingRegressor",
    "StackingClassifier",
    "StackingRegressor",
    "HistGradientBoostingClassifier",
    "HistGradientBoostingRegressor",
]
