# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/inspection/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.inspection._partial_dependence import partial_dependence as partial_dependence
from sklearn.inspection._permutation_importance import permutation_importance as permutation_importance
from sklearn.inspection._plot.decision_boundary import DecisionBoundaryDisplay as DecisionBoundaryDisplay
from sklearn.inspection._plot.partial_dependence import PartialDependenceDisplay as PartialDependenceDisplay

__all__ = [
    "partial_dependence",
    "permutation_importance",
    "PartialDependenceDisplay",
    "DecisionBoundaryDisplay",
]
