# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/feature_extraction/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.feature_extraction import image as image, text as text
from sklearn.feature_extraction._dict_vectorizer import DictVectorizer as DictVectorizer
from sklearn.feature_extraction._hash import FeatureHasher as FeatureHasher
from sklearn.feature_extraction.image import grid_to_graph as grid_to_graph, img_to_graph as img_to_graph

__all__ = [
    "DictVectorizer",
    "image",
    "img_to_graph",
    "grid_to_graph",
    "text",
    "FeatureHasher",
]
