# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/utils/_set_output.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from typing import Literal

from sklearn.base import BaseEstimator

class _SetOutputMixin:
    def __init_subclass__(cls, auto_wrap_output_keys: None | tuple[str] = ..., **kwargs) -> None: ...
    def set_output(self, *, transform: None | Literal["default", "pandas"] = None) -> BaseEstimator: ...
