# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/utils/metaestimators.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from abc import ABCMeta, abstractmethod
from contextlib import suppress as suppress
from operator import attrgetter as attrgetter
from typing import Any, ClassVar

from sklearn.base import BaseEstimator
from sklearn.utils._available_if import available_if

__all__ = ["available_if"]

class _BaseComposition(BaseEstimator, metaclass=ABCMeta):
    steps: ClassVar[list[Any]] = ...

    @abstractmethod
    def __init__(self) -> None: ...
