# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/utils/random.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
import array

# Author: Hamzeh Alsalhi <ha258@cornell.edu>
#
# License: BSD 3 clause
import numpy as np
import scipy.sparse as sp

from sklearn.utils import check_random_state as check_random_state
from sklearn.utils._random import sample_without_replacement

__all__ = ["sample_without_replacement"]
