# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/utils/stats.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
import numpy as np

from sklearn.utils.extmath import stable_cumsum as stable_cumsum
