from collections.abc import Callable, Iterable, Mapping
from typing import Any, Self

class Struct(dict[str, Any]):
    def __getattr__(self, key: str) -> Any: ...
    def __setattr__(self, key: str, value: Any) -> None: ...
    def __delattr__(self, key: str) -> None: ...
    def copy(self) -> Struct: ...
    def dict(self) -> dict[str, Any]: ...
    def allow_new_attr(self, allow: bool = True) -> None: ...
    def hasattr(self, key: str) -> bool: ...
    def merge(self, __loc_data__: Mapping[str, Any] | None = None,
              __conflict_solve: Mapping[Callable[[Any, Any], Any], str | list[str]] | None = None,
              **kw: Any) -> None: ...
    def __iadd__(self, other: Mapping[str, Any]) -> Self: ...
    def __add__(self, other: Mapping[str, Any]) -> Struct: ...
    def __isub__(self, other: Iterable[str]) -> Self: ...
    def __sub__(self, other: Iterable[str]) -> Struct: ...
