# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/svm/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.svm._bounds import l1_min_c as l1_min_c
from sklearn.svm._classes import (
    SVC as SVC,
    SVR as SVR,
    LinearSVC as LinearSVC,
    LinearSVR as LinearSVR,
    NuSVC as NuSVC,
    NuSVR as NuSVR,
    OneClassSVM as OneClassSVM,
)

__all__ = [
    "LinearSVC",
    "LinearSVR",
    "NuSVC",
    "NuSVR",
    "OneClassSVM",
    "SVC",
    "SVR",
    "l1_min_c",
]
