# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/decomposition/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.utils.extmath import randomized_svd as randomized_svd
from sklearn.decomposition._dict_learning import (
    DictionaryLearning as DictionaryLearning,
    MiniBatchDictionaryLearning as MiniBatchDictionaryLearning,
    SparseCoder as SparseCoder,
    dict_learning as dict_learning,
    dict_learning_online as dict_learning_online,
    sparse_encode as sparse_encode,
)
from sklearn.decomposition._factor_analysis import FactorAnalysis as FactorAnalysis
from sklearn.decomposition._fastica import FastICA as FastICA, fastica as fastica
from sklearn.decomposition._incremental_pca import IncrementalPCA as IncrementalPCA
from sklearn.decomposition._kernel_pca import KernelPCA as KernelPCA
from sklearn.decomposition._lda import LatentDirichletAllocation as LatentDirichletAllocation
from sklearn.decomposition._nmf import NMF as NMF, MiniBatchNMF as MiniBatchNMF, non_negative_factorization as non_negative_factorization
from sklearn.decomposition._pca import PCA as PCA
from sklearn.decomposition._sparse_pca import MiniBatchSparsePCA as MiniBatchSparsePCA, SparsePCA as SparsePCA
from sklearn.decomposition._truncated_svd import TruncatedSVD as TruncatedSVD

__all__ = [
    "DictionaryLearning",
    "FastICA",
    "IncrementalPCA",
    "KernelPCA",
    "MiniBatchDictionaryLearning",
    "MiniBatchNMF",
    "MiniBatchSparsePCA",
    "NMF",
    "PCA",
    "SparseCoder",
    "SparsePCA",
    "dict_learning",
    "dict_learning_online",
    "fastica",
    "non_negative_factorization",
    "randomized_svd",
    "sparse_encode",
    "FactorAnalysis",
    "TruncatedSVD",
    "LatentDirichletAllocation",
]
