# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/decomposition/_base.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from abc import ABCMeta, abstractmethod
from typing_extensions import Self

from numpy import ndarray

from sklearn._typing import MatrixLike
from sklearn.base import BaseEstimator, ClassNamePrefixFeaturesOutMixin, TransformerMixin

# Author: Alexandre Gramfort <alexandre.gramfort@inria.fr>
#         Olivier Grisel <olivier.grisel@ensta.org>
#         Mathieu Blondel <mathieu@mblondel.org>
#         Denis A. Engemann <denis-alexander.engemann@inria.fr>
#         Kyle Kastner <kastnerkyle@gmail.com>
#
# License: BSD 3 clause

class _BasePCA(ClassNamePrefixFeaturesOutMixin, TransformerMixin, BaseEstimator, metaclass=ABCMeta):
    def get_covariance(self) -> ndarray: ...
    def get_precision(self) -> ndarray: ...
    @abstractmethod
    def fit(self, X: MatrixLike, y=None) -> Self: ...
    def transform(self, X: MatrixLike) -> ndarray: ...
    def inverse_transform(self, X: MatrixLike) -> ndarray: ...
