"""scikit-learn 1.9 estimator contracts; see typings/README.md."""

from collections.abc import Callable, Mapping
from typing import Any, ClassVar, Literal, Protocol, Self, overload

import numpy as np
from numpy.typing import ArrayLike, NDArray

from sklearn._typing import Float, Int, MatrixLike
from sklearn.utils._metadata_requests import _MetadataRequester
from sklearn.utils._set_output import _SetOutputMixin

class _Parameterized(Protocol):
    def get_params(self, deep: bool = True) -> Mapping[str, object]: ...

class _CloneHook(Protocol):
    def __sklearn_clone__(self) -> Self: ...

@overload
def clone[_T: _Parameterized | _CloneHook](estimator: _T, *, safe: bool = True) -> _T: ...
@overload
def clone[_T](estimator: list[_T], *, safe: bool = True) -> list[_T]: ...
@overload
def clone[_T](estimator: tuple[_T, ...], *, safe: bool = True) -> tuple[_T, ...]: ...
@overload
def clone[_T](estimator: set[_T], *, safe: bool = True) -> set[_T]: ...
@overload
def clone[_T](estimator: frozenset[_T], *, safe: bool = True) -> frozenset[_T]: ...
@overload
def clone[_K, _V](estimator: dict[_K, _V], *, safe: bool = True) -> dict[_K, _V]: ...
@overload
def clone[_T](estimator: _T, *, safe: Literal[False]) -> _T: ...

class BaseEstimator(_MetadataRequester):
    def __init__(self) -> None: ...
    def get_params(self, deep: bool = True) -> dict[str, object]: ...
    def set_params(self, **params: object) -> Self: ...
    def __sklearn_clone__(self) -> Self: ...
    def __repr__(self, N_CHAR_MAX: int = 700) -> str: ...
    def __getstate__(self) -> dict[str, Any]: ...
    def __setstate__(self, state: dict[str, Any]) -> None: ...

class ClassifierMixin:
    _estimator_type: ClassVar[str]
    def score(self, X: MatrixLike, y: MatrixLike | ArrayLike,
              sample_weight: ArrayLike | None = None) -> Float: ...

class RegressorMixin:
    _estimator_type: ClassVar[str]
    def score(self, X: MatrixLike, y: MatrixLike | ArrayLike,
              sample_weight: ArrayLike | None = None) -> Float: ...

class ClusterMixin:
    _estimator_type: ClassVar[str]
    def fit_predict(self, X: MatrixLike, y: Any = None, **kwargs: Any) -> NDArray[np.integer[Any]]: ...

class BiclusterMixin:
    @property
    def biclusters_(self) -> tuple[NDArray[np.bool_], NDArray[np.bool_]]: ...
    def get_indices(self, i: Int) -> tuple[NDArray[np.intp], NDArray[np.intp]]: ...
    def get_shape(self, i: Int) -> tuple[int, int]: ...
    def get_submatrix(self, i: Int, data: MatrixLike) -> MatrixLike: ...

class TransformerMixin(_SetOutputMixin):
    def fit_transform(self, X: MatrixLike, y: MatrixLike | ArrayLike | None = None,
                      **fit_params: Any) -> MatrixLike: ...

class OneToOneFeatureMixin:
    def get_feature_names_out(self, input_features: ArrayLike | None = None) -> NDArray[np.object_]: ...

class ClassNamePrefixFeaturesOutMixin:
    def get_feature_names_out(self, input_features: ArrayLike | None = None) -> NDArray[np.object_]: ...

class DensityMixin:
    _estimator_type: ClassVar[str]
    def score(self, X: MatrixLike, y: Any = None) -> float: ...

class OutlierMixin:
    _estimator_type: ClassVar[str]
    def fit_predict(self, X: MatrixLike | ArrayLike, y: Any = None,
                    **kwargs: Any) -> NDArray[np.integer[Any]]: ...

class MetaEstimatorMixin: ...
class MultiOutputMixin: ...
class _UnstableArchMixin: ...

def is_classifier(estimator: object) -> bool: ...
def is_regressor(estimator: object) -> bool: ...
def is_clusterer(estimator: object) -> bool: ...
def is_outlier_detector(estimator: object) -> bool: ...
def _fit_context[**_P, _R](
    *, prefer_skip_nested_validation: bool
) -> Callable[[Callable[_P, _R]], Callable[_P, _R]]: ...
