# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/linear_model/_glm/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.linear_model._glm.glm import (
    GammaRegressor as GammaRegressor,
    PoissonRegressor as PoissonRegressor,
    TweedieRegressor as TweedieRegressor,
    _GeneralizedLinearRegressor as _GeneralizedLinearRegressor,
)

# License: BSD 3 clause

__all__ = [
    "_GeneralizedLinearRegressor",
    "PoissonRegressor",
    "GammaRegressor",
    "TweedieRegressor",
]
