# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/gaussian_process/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.gaussian_process import kernels as kernels
from sklearn.gaussian_process._gpc import GaussianProcessClassifier as GaussianProcessClassifier
from sklearn.gaussian_process._gpr import GaussianProcessRegressor as GaussianProcessRegressor

# Author: Jan Hendrik Metzen <jhm@informatik.uni-bremen.de>
#         Vincent Dubourg <vincent.dubourg@gmail.com>
#         (mostly translation, see implementation details)
# License: BSD 3 clause

__all__ = ["GaussianProcessRegressor", "GaussianProcessClassifier", "kernels"]
