# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/_loss/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn._loss.loss import (
    AbsoluteError as AbsoluteError,
    HalfBinomialLoss as HalfBinomialLoss,
    HalfGammaLoss as HalfGammaLoss,
    HalfMultinomialLoss as HalfMultinomialLoss,
    HalfPoissonLoss as HalfPoissonLoss,
    HalfSquaredError as HalfSquaredError,
    HalfTweedieLoss as HalfTweedieLoss,
    HalfTweedieLossIdentity as HalfTweedieLossIdentity,
    PinballLoss as PinballLoss,
)

__all__ = [
    "HalfSquaredError",
    "AbsoluteError",
    "PinballLoss",
    "HalfPoissonLoss",
    "HalfGammaLoss",
    "HalfTweedieLoss",
    "HalfTweedieLossIdentity",
    "HalfBinomialLoss",
    "HalfMultinomialLoss",
]
