# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/feature_selection/_variance_threshold.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from typing import Any, ClassVar
from typing_extensions import Self

from numpy import ndarray

from sklearn._typing import Float, MatrixLike
from sklearn.base import BaseEstimator
from sklearn.feature_selection._base import SelectorMixin

# Author: Lars Buitinck
# License: 3-clause BSD

class VarianceThreshold(SelectorMixin, BaseEstimator):
    feature_names_in_: ndarray = ...
    n_features_in_: int = ...
    variances_: ndarray = ...

    _parameter_constraints: ClassVar[dict] = ...

    def __init__(self, threshold: Float = 0.0) -> None: ...
    def fit(self, X: MatrixLike, y: Any = None) -> Self: ...
