# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/cluster/_feature_agglomeration.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from numpy import ndarray

from sklearn._typing import ArrayLike, MatrixLike
from sklearn.base import TransformerMixin

# Author: V. Michel, A. Gramfort
# License: BSD 3 clause

###############################################################################
# Mixin class for feature agglomeration.

class AgglomerationTransform(TransformerMixin):
    def transform(self, X: MatrixLike) -> ndarray: ...
    def inverse_transform(self, Xred: MatrixLike | ArrayLike) -> ndarray: ...
