# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/semi_supervised/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.semi_supervised._label_propagation import LabelPropagation as LabelPropagation, LabelSpreading as LabelSpreading
from sklearn.semi_supervised._self_training import SelfTrainingClassifier as SelfTrainingClassifier

__all__ = ["SelfTrainingClassifier", "LabelPropagation", "LabelSpreading"]
