# Based on scikit-learn-stubs 0.0.3, sklearn-stubs/manifold/__init__.pyi.
# Generated by typings/build_overlays.py; see typings/README.md.
from sklearn.manifold._isomap import Isomap as Isomap
from sklearn.manifold._locally_linear import (
    LocallyLinearEmbedding as LocallyLinearEmbedding,
    locally_linear_embedding as locally_linear_embedding,
)
from sklearn.manifold._mds import MDS as MDS, smacof as smacof
from sklearn.manifold._spectral_embedding import SpectralEmbedding as SpectralEmbedding, spectral_embedding as spectral_embedding
from sklearn.manifold._t_sne import TSNE as TSNE, trustworthiness as trustworthiness

__all__ = [
    "locally_linear_embedding",
    "LocallyLinearEmbedding",
    "Isomap",
    "MDS",
    "smacof",
    "SpectralEmbedding",
    "spectral_embedding",
    "TSNE",
    "trustworthiness",
]
